---
- name: Create Instance in Azure
  hosts: localhost
  connection: local
  gather_facts: false
  become: no

  tasks:
  - name: Create a public ip address
    azure_rm_publicipaddress:
      resource_group: "Student{{ student_number }}"
      name: "Student{{ student_number }}-PubIP{{ virtual_machine_num }}"
      allocation_method: Dynamic
      domain_name: "student{{ student_number }}vm{{ virtual_machine_num }}"

  - name: Create a network interface using existing security group and public IP
    azure_rm_networkinterface:
      name: "Student{{ student_number }}-NI{{ virtual_machine_num }}"
      resource_group: "Student{{ student_number }}"
      virtual_network: "Student{{ student_number }}-Network"
      subnet_name: "Student{{ student_number }}-Subnet"
      security_group: "Student{{ student_number }}-SG"
      cert_validation_mode: ignore
      ip_configurations:
        - name: "student{{ student_number }}.ipconfig{{ virtual_machine_num }}"
          private_ip_allocation_method: Dynamic
          public_ip_address_name: "student{{ student_number }}vm{{ virtual_machine_num }}"

  - name: Create Azure RHEL Virtual Machine
    azure_rm_virtualmachine:
      resource_group: "Student{{ student_number }}"
      name: "Student{{ student_number }}vm{{ virtual_machine_num }}"
      vm_size: Standard_B2s
      admin_username: "student{{ student_number }}"
      admin_password: RedHatSNX123!
      network_interface_names: "Student{{ student_number }}-NI{{ virtual_machine_num }}"
      image:
        offer: RHEL
        publisher: RedHat
        sku: '7-RAW'
        version: latest
